name: Build and Deploy Backend

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: 'gradle'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew build -x test
    
    - name: Find JAR file
      run: |
        JAR_FILE=$(find ${{ github.workspace }}/build/libs -name "*.jar" | grep -v "plain")
        echo "DEPLOY_JAR_PATH=$JAR_FILE" >> $GITHUB_ENV
    
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: '${{ env.DEPLOY_JAR_PATH }}'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: java-app
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_32D34A60B0864E2D821F28570AC57038 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_00CD991C0FB042F8AC049908BEB53F1C }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2EA9B5704C004D459DCA2F2265EFFEE3 }}
    
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'husibackend'
        package: '*.jar'
